export const CAROUSELS = [
  {
    url: 'http://picsum.photos/600.jpg',
    name: 'carousel 1',
  },
  {
    url: 'public/carouse-3.jpeg',
    name: 'carousel 2',
  },
  {
    url: './carouse-3.jpeg',
    name: 'carousel 3',
  },
];

// 10 wota
export const TRENDINGS = [
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: 'Movie description',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
];

// 5 - 6 wota
export const FROM_US = [
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
];

// 5 - 6
export const TOP_GROSS = [
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['https://picsum.photos/600', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: '',
  },
];

// 8 wota
export const NEWS = [
  {
    id: 1,
    title: 'THis is news title',
    excerpt: 'THis si excerpt',
    description: 'THis is long description',
    dateCreated: '2020/05/10',
    imageUrl: '',
  },
  {
    id: 1,
    title: 'THis is news title',
    excerpt: 'THis si excerpt',
    description: 'THis is long description',
    dateCreated: '2020/05/10',
    imageUrl: '',
  },
  {
    id: 1,
    title: 'THis is news title',
    excerpt: 'THis si excerpt',
    description: 'THis is long description',
    dateCreated: '2020/05/10',
    imageUrl: '',
  },
  {
    id: 1,
    title: 'THis is news title',
    excerpt: 'THis si excerpt',
    description: 'THis is long description',
    dateCreated: '2020/05/10',
    iamgeUrl: '',
  },
];

// 20 wota
export const MOVIES = [
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['http', ''], // minimum 3
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: 'Movie description',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: 'Movie description',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: 'Movie description',
  },
  {
    id: 1,
    title: 'Avatar',
    rating: 4.1,
    director: 'James Cameron',
    genre: ['Sci-Fi', 'jiji'],
    imageUrls: ['', ''],
    excerpt: 'short description',
    grossIncome: 152222,
    year: 1999,
    writers: ['Sci-Fi', 'jiji'],
    stars: ['Scifi', 'asdas'],
    description: 'Movie description',
  },
];
